name: transpile tsc

on:
  push: #Event
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current working directory
        run: pwd

      - name: check current folder list
        run: ls -all

      - name: install typescript
        run: npm install typescript

      - name: check typescript version
        run: tsc -v

      - name: transpile .ts into .js
        run: tsc

      - name: check current folder list
        run: ls

      - name: check dist/index.ts
        run: ls -i dist

      - name: check git remote
        run: git remote -v

      - name: print git envirable
        run: |
          echo "Github Context"
          echo "${{ toJson(github) }}" | jq .

      # - name: login git
      #   run: |
      #   git config --global user.name "ahn0min"
      #   git config --global user.email "ahn0min95@gmail.com"
      #   git add dist
      #   git commit -m "build: result build"
      #   git push origin ${{ github.ref }}

      ## 성공했을때를 가정

      # - name:
