name: transpile tsc

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  # push:
  # branches:
  # - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install typescript
        run: npm install typescript

      - name: transpile .ts into .js
        run: |
          tsc
          ls -i dist
      - name: check git remote
        run: |
          git remote -v
          git branch -r
          echo "Local Branch List"
          git branch
      - name: login git
        run: |
          git config --global init.defaultBranch main
          echo "${{ github.ref }}""
          git pull origin ${{ github.ref }}
          git add dist
          git config --global user.name "0min"
          git config --global user.email "ahn0min95@gmail.com"

          echo "github.ref ${{ github.ref }}"
          echo "github.base_ref ${{ github.base_ref }}"

          if [ "$(git diff --cached --name-only)" ]; then
            echo "Staged changes detected. Committing and pushing..."
            echo "${{ github }}"
            git commit -m "chore: compile .ts into .js"
            git push origin ${{ github.base_ref }}
            
          else
            echo "No staged status file"
          fi

        # echo Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}"
