name: transpile tsc

on:
  push:
    branches:
      - main
      - feat/1
      - feat/2

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install typescript
        run: npm install typescript

      - name: check typescript version
        run: tsc -v

      - name: transpile .ts into .js
        run: |
          tsc
          ls -i dist

      - name: check git remote
        run: |
          git remote -v
          git branch -r

      - name: login git
        run: |
          echo "${{ github.ref }}"
          git add dist
          git config --global user.name "ahn0min"
          git config --global user.email "ahn0min95@gmail.com"
          git commit -m "build: result build"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# git config --global user.name "ahn0min"
# git config --global user.email "ahn0min95@gmail.com"
