name: transpile tsc

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  # push:
  # branches:
  # - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install typescript
        run: npm install typescript

      # - name: transpile .ts into .js
      #   run: |
      #     tsc
      #     ls -i dist
      - name: login git
        run: |
          git branch
          git checkout -t origin/"${{ github.head_ref}}"
          git pull

          tsc
          git add dist

          git config --global user.name "0min"
          git config --global user.email "ahn0min95@gmail.com"

          if [ "$(git diff --cached --name-only)" ]; then
            echo "Staged changes detected. Committing and pushing..."
            echo "${{ toJson(github) }}"
            git commit -m "chore: compile .ts into .js"
            git push origin "${{ github.head_ref }}"
            
          else
            echo "No staged status file"
          fi

        #echo "github.ref ${{ github.ref }}"
        #echo "github.base_ref ${{ github.base_ref }}"
        #echo "github.head_ref ${{ github.head_ref }}"
        #echo "github.event ${{ github.head_ref }}"

        # git config --global init.defaultBranch main
        # echo "${{ github.ref }}"
        # git pull origin "${{ github.ref }}"

        # echo Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}"
