name: transpile tsc

on:
  push: #Event
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: install typescript
        run: npm install typescript

      - name: check typescript version
        run: tsc -v

      - name: Check current working directory
        run: pwd

      - name: check current folder list
        run: ls -all

      - name: refresh remote branch
        run: git pull origin master

      - name: transpile .ts into .js
        run: tsc index.ts
