name: transpile tsc

on:
  push: #Event
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current working directory
        run: pwd

      - name: check current folder list
        run: ls -all

      - name: install typescript
        run: npm install typescript

      - name: check typescript version
        run: tsc -v

      - name: transpile .ts into .js
        run: tsc

      - name: check current folder list
        run: ls

      - name: check dist/index.ts
        run: ls -i dist

  check-compiled:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: check current folder list
        run: ls

      - name: check dist/index.ts
        run: ls -i dist
