name: transpile tsc

on:
  push: #Event
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: install typescript
        run: npm install typescript

      - name: print tsc
        run: tsc -v
